export const SlotEvents = {
    UPDATE_BET_BALANCE : "UpdateBetBalance",
    UPDATE_BALANCE : "UpdateBalance",
    UPDATE_BETDEDUCTED_BALANCE : "UpdateBetDeductedBalance",
    ACTIVATE_GAME : "ActivateGame",
    SET_INITIAL_VALUES : "SetInitialValues",
    STAKE_CHANGE : "StakeChange",
    UPDATE_BET_VALUE : "UpdateBetValue",
    SPIN_CLICKED : "SpinClicked",
    STOP_SPIN_CLICKED : "StopSpinClicked",
    BET_CLICKED : "BetClicked",
    AUTOSPIN_CLICKED : "AutospinClicked",
    TOURNAMENT_ICON_CLICKED : "TournamentIconClicked",
    SHOW_AUTOSPIN_DIALOGUE : "ShowAutospinDialogue",
    STOP_AUTOSPIN : "StopAutospin",
    AUTOSPIN_SELECTED : "AutospinSelected",
    DISABLE_ALL_BUTTONS : "DisableAllButtons",
    DO_FULLSCREEN : "DoFullScreen",
    DO_GAME_FULLSCREEN : "DoGameFullscreen",
    SET_SPIN_CONTROLLER : "SetSpinController",
    SET_WIN_CONTROLLER : "SetWinController",
    START_SLOT_SPIN : "StartSlotSpin",
    SPIN_RESPONSE_RECEIVED : "SpinResponseReceived",
    FEATURE_RESPONSE_RECEIVED : "FeatureResponseReceived",
    HANDLE_FEATURE_RESPONSE_IN_GAME : "HandleFeatureResponseInGame",
    START_STOPPING_REELS : "StartStoppingReels",
    STOP_SPIN_IMMEDIATELY : "StopSpinImmediately",
    STOP_SPIN_FOR_ERROR : "StopSpinForError",
    REELSTRIP_SPIN_STARTED : "ReelstripSpinStarte",
    REELSTRIP_SPIN_COMPLETED : "ReelStripSpinCompleted",
    REELSTRIP_SINGLE_SPIN_COMPLETED : "ReelStripSingleSpinCompleted",
    REELSTRIP_SPIN_JERK : "ReelstripSpinJerk",
    HIDE_SPINSTOP_BUTTON : "HideSpinStopButton",
    REELSPIN_COMPLETED : "ReelSpinCompleted",
    SHOW_BET_SELECTION_DIALOGUE : "ShowBetSelectionDialogue",
    SHOW_MOBILE_SETTINGS_DIALOGUE : "ShowMobileSettingsDialogue",
    FADEOUT_PRELOADER : "FadeoutPreloader",
    REMOVE_PRELOADER : "RemovePreloader",
    PLAY_ANTICIPATION_SOUND : "PlayAnticipationSound",
    STOP_ANTICIPATION_SOUND : "StopAnticipationSound",

    SHOW_PAYTABLE : "ShowPaytable",
    DESKTOP_SETTINGS_CLICKED : "DesktopSettingsClicked",
    SHOW_DESKTOP_SETTINGS : "ShowDesktopSettings",

    ENTER_SPINWIN_STATE : "EnterSpinWinState",
    EXIT_SPINWIN_STATE : "ExitSpinWinState",
    ENTER_FEATURE_STATE : "EnterFeatureState",
    EXIT_FEATURE_STATE : "ExitFeatureState",
    EXIT_SPINWIN_SYMBOL : "ExitSpinWinSymbol",
    EXIT_SPINWIN_AMOUNT : "ExitSpinWinAmount",
    SHOW_SLOT_BIG_WIN : "ShowSlotBigWin",
    CLEAR_SLOT_BIG_WIN : "ClearSlotBigWin",
    NORMAL_WIN_COUNTUP_DONE: "NormalWinCountUpDone",
    SHOW_50AK_WIN: "ShowFiveOfAKindWin",
    FIVEOAK_WIN_COMPLETED: "FiveOAKWinCompleted",
    SLOT_MACHINE_POSITIONED : "SlotMachinePositioned",
    SHOW_LINE_WIN : "ShowLineWin",
    EXIT_LINE_WIN : "ExitLineWin",
    CLEAR_ALL_WIN : "ClearAllWin",
    STOP_CUSTOM_WIN_ANIMATION : "StopCustomWinAnimation",
    RESTART_CUSTOM_WIN_ANIMATION : "RestartCustomWinAnimation",
    CLEAR_TRIGGERING_ANIM : "ClearTriggeringAnim",
    CLEAR_GAME_FOR_SPIN : "ClearGameForSpin",
    CLEAR_WIN_ANIMS : "clearWinAnimations",
    SHOW_MESSAGE_POPUP : "ShowMessagePopup",
    HIDE_MESSAGE_POPUP : "HideMessagePopup",
    SHOW_BUYBONUS_POPUP : "ShowBuyBonusPopup",
    HIDE_BUYBONUS_POPUP : "HideBuyBonusPopup",
    REPLACE_REEL_WITH_SYMBOLS : "ReplaceReelWithSymbols",
    SHOW_SLOTMACHINE : "ShowHideSlotMachine",
    SHOW_SLOTPANEL : "ShowHideSlotPanel",
    SHOW_SLOTMACHINE_AND_PANEL : "ShowSlotMachineAndPanel",
    NOTIFY_BONUS_ROUND_END : "NotifyBonusRoundEnd",
    SHOW_HIDE_SLOT_SYMBOLS : "ShowHideSlotSymbols",
    SHOW_HIDE_SLOT_GAMETITLE : "ShowHideGameTitle",
    REPLACE_REEL_SYMBOLS : "ReplaceReelSymbols",
    REPLACE_REEL_SYMBOLS_FOR_REEL : "ReplaceReelSymbolsForReel",

    NOTIFY_FS_ENTRY_SHOWN : "NotifyFSEntryShown",

    UPDATE_UI_FOR_AUTOSPIN_START : "UpdateUIForAutospinStart",
    UPDATE_UI_FOR_AUTOSPIN_END : "UpdateUIForAutospinEnd",
    UPDATE_AUTOSPIN_COUNT : "UpdateAutospinCount",
    VALIDATE_TOURNEY_ICON : "ValidateTourneyIcon",
    TOURNAMENT_PRIZE_UPDATE: "TournamentPrizeUpdate",
    SHOW_MAINGAME_BG : "ShowMaingameBG",
    SHOW_FREEGAME_BG : "ShowFreegameBG",
    SHOW_BONUSGAME_BG : "ShowBonusgameBG",
    SHOW_SPLASH_BG : "ShowSplashBG",
    TRIGGER_FEATURE : "TriggerFeature",
    SHOW_SELECT_BONUS : "ShowSelectBonus",
    INITIATE_BONUS_ROUND : "InitiateBonusRound",
    HIDE_BONUS_ROUND : "HideBonusRound",
    SHOW_BONUS_TRIGGERING_ANIM : "ShowBonusTriggeringAnim",
    SHOW_CUSTOM_BONUS_TRIGGERING_ANIM : "ShowCustomBonusTriggeringAnim",
    SHOW_CUSTOM_TRIGGERING_ANIM : "ShowCustomTriggerAnim",
    TRIGGER_FREESPIN : "TriggerFreespin",
    GAME_START_CLICKED : "GameStartClicked",
    GAME_START_CLICKED_SKIPPED : "GameStartClickedSkipped",
    START_MAINGAME_BG_MUSIC : "StartMainGameBGMusic",
    STOP_MAINGAME_BG_MUSIC : "StopMainGameBGMusic",
    START_BONUS_BG_MUSIC : "StartBonusGameBGMusic",
    STOP_BONUS_BG_MUSIC : "StopBonusGameBGMusic",
    START_FREESPIN_BG_MUSIC : "StartFreespinGameBGMusic",
    STOP_FREESPIN_BG_MUSIC : "StopFreespinGameBGMusic",
    SHOW_FREESPIN_BIG_WIN : "ShowFreeSpinBigWin",
    PLAY_GENERIC_BUTTON_SOUND : "PlayGenericButtonSound",
    PLAY_REELSTOP_SOUND : "PlayReelStopSound",
    PLAY_ALL_WIN_SOUND : "PlayAllWinSound",
    PLAY_ALL_WIN_SOUND_BIGWIN : "PlayAllWinSoundBigWin",
    PLAY_CROWD_CHEERING_BIGWIN : "PlayCrowdCheeringBigWin",
    STOP_CROWD_CHEERING_BIGWIN : "StopCrowdCheeringBigWin",
    FADEOUT_BG_MUSIC : "fadeOutBGMusic",
    STOP_ALL_WIN_SOUND_BIGWIN : "StopAllWinSoundBigWin",
    PLAY_LINEWIN_SOUND : "PlayLineWinSound",
    SELECT_BONUS_OPTION_SELECTED : "SelectBonusOptionSelected",
    SHOW_DICE_ANIMATION: "SHOW_DICE_ANIMATION",

    UPDATE_UI_FOR_FS_START : "UpdateUIForFSStart",
    UPDATE_UI_FOR_FS_END : "UpdateUIForFSEnd",
    UPDATE_UI_FOR_FS_ROUNDS : "UpdateUIForFSRounds",
    LOCALDATA_STATE_CHANGE : "LocalDataStateChange",
    PANEL_RESIZED : "PanelResized",

    HANDLE_BACCARAT_SOCKET_MESSAGE : "HandleBaccaratSocketMessage",
    SHOW_ALERT_POPUP : "ShowAlertPopup",
    HIDE_ALERT_POPUP : "HideAlertPopup",
    BUY_BONUS_CLICKED : "BuyBonusClicked",
    IOS_SOUND_YES_CLICKED : "IOSSoundYesClicked",
    IOS_SOUND_NO_CLICKED : "IOSSoundNoClicked",
    TG_BUTTON_CLICKED : "TGButtonClicked",
    LANDING_SYMBOL_ANIMATION : "LandingSymbolAnimation",

    SHOW_PAYLINE : "ShowPayline",
    HIDE_PAYLINE : "HidePayline",

    COIN_CASH_MODE_CHANGED: "CoinCashModeChanged",

    WINDOW_RESIZE:"WINDOW_RESIZE"
}
